# Generated by Django 5.2.4 on 2025-07-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField(verbose_name='Instrucción')),
                ('input_file', models.FileField(upload_to='input_excels/', verbose_name='Archivo de entrada')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='output_excels/', verbose_name='Archivo de salida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Documento Excel',
                'verbose_name_plural': 'Documentos Excel',
            },
        ),
    ]
